from __future__ import annotations

from sqlalchemy.orm import Session

from models.procedimento import Procedimento
from models.procedimento_tabela import ProcedimentoTabela
from models.procedimento_generico import ProcedimentoGenerico


PROCEDIMENTOS_PADRAO = [{'codigo': 1,
  'nome': 'ABERTURA IMPLANTE',
  'tempo': 45,
  'preco': 300.0,
  'custo': 34.334999999999994,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': 'INTERVENCAO',
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': '17/03/2026 11:23',
  'data_alteracao': '17/03/2026 11:23'},
 {'codigo': 2,
  'nome': 'AUMENTO DE COROA CLINICA',
  'tempo': 60,
  'preco': 450.0,
  'custo': 75.46500000000002,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 3,
  'nome': 'BIOMATERIAL',
  'tempo': 60,
  'preco': 1100.0,
  'custo': 396.23499999999996,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 4,
  'nome': 'BOTOX',
  'tempo': 45,
  'preco': 1200.0,
  'custo': 515.0399999999998,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 5,
  'nome': 'CIMENTAÇÃO AD.',
  'tempo': 30,
  'preco': 200.0,
  'custo': 52.44999999999999,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 6,
  'nome': 'CIMENTAÇÃO COROA T',
  'tempo': 30,
  'preco': 150.0,
  'custo': 8.17,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 7,
  'nome': 'CIRURGIA CISTO',
  'tempo': 90,
  'preco': 550.0,
  'custo': 65.045,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 8,
  'nome': 'CIRURGIA EXPLORATÓRIA',
  'tempo': 90,
  'preco': 500.0,
  'custo': 65.215,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 9,
  'nome': 'CLAREAMENTO CASEIRO',
  'tempo': 90,
  'preco': 800.0,
  'custo': 79.0,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 10,
  'nome': 'CLAREAMENTO CONSULTÓRIO',
  'tempo': 100,
  'preco': 1500.0,
  'custo': 100.34,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 11,
  'nome': 'CONSULTA DE EMERGÊNCIA',
  'tempo': 60,
  'preco': 450.0,
  'custo': 18.845,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 12,
  'nome': 'CONSULTA INICIAL',
  'tempo': 45,
  'preco': 350.0,
  'custo': 6.27,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 13,
  'nome': 'COROA METALO-C',
  'tempo': 120,
  'preco': 1500.0,
  'custo': 580.925,
  'custo_lab': 500.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 14,
  'nome': 'COROA PROVISÓRIA IMEDIATA',
  'tempo': 60,
  'preco': 350.0,
  'custo': 38.29499999999999,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 15,
  'nome': 'COROA PROVISÓRIA LAB',
  'tempo': 90,
  'preco': 500.0,
  'custo': 142.635,
  'custo_lab': 71.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 16,
  'nome': 'COROA SOB IMP',
  'tempo': 120,
  'preco': 1900.0,
  'custo': 656.985,
  'custo_lab': 500.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 17,
  'nome': 'COROA ZIRCONIA',
  'tempo': 120,
  'preco': 1550.0,
  'custo': 639.88,
  'custo_lab': 550.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 18,
  'nome': 'E-MAX INLAY-ONLAY',
  'tempo': 120,
  'preco': 1900.0,
  'custo': 628.92,
  'custo_lab': 533.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 19,
  'nome': 'ENDO INCISIVOS',
  'tempo': 90,
  'preco': 500.0,
  'custo': 57.764999999999986,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 20,
  'nome': 'ENDO MOLAR',
  'tempo': 120,
  'preco': 1000.0,
  'custo': 68.76499999999999,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 21,
  'nome': 'ENDO PRÉ',
  'tempo': 90,
  'preco': 700.0,
  'custo': 55.454999999999984,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 22,
  'nome': 'ENXERTO + TUNELIZAÇÃO',
  'tempo': 150,
  'preco': 1500.0,
  'custo': 179.67499999999998,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 23,
  'nome': 'ENXERTO CONJUNTIVO LIVRE',
  'tempo': 150,
  'preco': 1500.0,
  'custo': 88.31499999999998,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 24,
  'nome': 'EXODONTIA',
  'tempo': 60,
  'preco': 350.0,
  'custo': 65.215,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 25,
  'nome': 'FACETAS',
  'tempo': 120,
  'preco': 2300.0,
  'custo': 654.545,
  'custo_lab': 533.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 26,
  'nome': 'FRENECTOMIA',
  'tempo': 75,
  'preco': 750.0,
  'custo': 73.00500000000001,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 27,
  'nome': 'GENGIVECTOMIA',
  'tempo': 60,
  'preco': 500.0,
  'custo': 71.42500000000001,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 28,
  'nome': 'GUIA CIRURGICO',
  'tempo': 45,
  'preco': 500.0,
  'custo': 201.27,
  'custo_lab': 195.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 29,
  'nome': 'IMPLANTE + BIOMATERIAL',
  'tempo': 90,
  'preco': 2000.0,
  'custo': 519.1850000000001,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 30,
  'nome': 'IMPLANTE OST',
  'tempo': 75,
  'preco': 800.0,
  'custo': 189.185,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 31,
  'nome': 'IMPLANTE+PROTOCOLO',
  'tempo': 240,
  'preco': 8500.0,
  'custo': 3614.92,
  'custo_lab': 2300.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 32,
  'nome': 'INLAY-ONLAY',
  'tempo': 120,
  'preco': 1200.0,
  'custo': 350.91999999999996,
  'custo_lab': 255.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 33,
  'nome': 'INSTRUÇÃO HIG',
  'tempo': 60,
  'preco': 250.0,
  'custo': 6.739999999999999,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 34,
  'nome': 'LEVANTAMENTO DE SEIO',
  'tempo': 120,
  'preco': 3500.0,
  'custo': 1543.0749999999998,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 35,
  'nome': 'NÚCLEO DE PREENCHIMENTO',
  'tempo': 60,
  'preco': 250.0,
  'custo': 32.019999999999996,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 36,
  'nome': 'NÚCLEO FIBRA DE VIDRO',
  'tempo': 60,
  'preco': 450.0,
  'custo': 61.544999999999995,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 37,
  'nome': 'NÚCLEO METALICO FUNDIDO',
  'tempo': 60,
  'preco': 450.0,
  'custo': 136.75,
  'custo_lab': 110.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 38,
  'nome': 'PLACA DE MORDIDA',
  'tempo': 45,
  'preco': 350.0,
  'custo': 37.01999999999999,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 39,
  'nome': 'PPF MPSI',
  'tempo': 120,
  'preco': 3000.0,
  'custo': 949.085,
  'custo_lab': 600.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 40,
  'nome': 'PPF PROV LAB',
  'tempo': 120,
  'preco': 1950.0,
  'custo': 222.15499999999997,
  'custo_lab': 150.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 41,
  'nome': 'PPR',
  'tempo': 120,
  'preco': 1500.0,
  'custo': 533.33,
  'custo_lab': 500.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 42,
  'nome': 'PPR PROV',
  'tempo': 60,
  'preco': 650.0,
  'custo': 220.99,
  'custo_lab': 190.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 43,
  'nome': 'PREENCHEDOR',
  'tempo': 45,
  'preco': 2000.0,
  'custo': 520.3399999999999,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 47,
  'nome': 'PROFILAXIA',
  'tempo': 60,
  'preco': 300.0,
  'custo': 10.970000000000002,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 48,
  'nome': 'PRÓTESE FIXA ADESIVA',
  'tempo': 120,
  'preco': 4500.0,
  'custo': 1589.67,
  'custo_lab': 1500.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 49,
  'nome': 'PRÓTESE PROTOCOLO',
  'tempo': 120,
  'preco': 8000.0,
  'custo': 2805.61,
  'custo_lab': 2000.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 50,
  'nome': 'PRÓTESE TOTAL',
  'tempo': 120,
  'preco': 1650.0,
  'custo': 444.80999999999995,
  'custo_lab': 311.5,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 51,
  'nome': 'PT IMEDIADA',
  'tempo': 120,
  'preco': 1200.0,
  'custo': 444.80999999999995,
  'custo_lab': 311.5,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 52,
  'nome': 'RASPAGEM',
  'tempo': 60,
  'preco': 500.0,
  'custo': 14.095000000000002,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 53,
  'nome': 'REEMBASAMENTO REPARO',
  'tempo': 45,
  'preco': 150.0,
  'custo': 9.8,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 54,
  'nome': 'RESTAURAÇÃO',
  'tempo': 120,
  'preco': 1200.0,
  'custo': 132.345,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 55,
  'nome': 'RESTAURAÇÃO 1',
  'tempo': 45,
  'preco': 300.0,
  'custo': 73.145,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 56,
  'nome': 'RESTAURAÇÃO 2',
  'tempo': 60,
  'preco': 600.0,
  'custo': 87.945,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 57,
  'nome': 'RESTAURAÇÃO 3',
  'tempo': 90,
  'preco': 900.0,
  'custo': 113.84499999999998,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 58,
  'nome': 'RETORNO',
  'tempo': 60,
  'preco': 250.0,
  'custo': 6.27,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None},
 {'codigo': 60,
  'nome': 'TRAÇÃO ORTO',
  'tempo': 90,
  'preco': 600.0,
  'custo': 64.46499999999999,
  'custo_lab': 0.0,
  'lucro_hora': 0.0,
  'especialidade': None,
  'procedimento_generico_codigo': None,
  'simbolo_grafico': None,
  'simbolo_grafico_legacy_id': None,
  'mostrar_simbolo': False,
  'garantia_meses': 0,
  'forma_cobranca': None,
  'valor_repasse': 0.0,
  'preferido': False,
  'inativo': False,
  'observacoes': None,
  'data_inclusao': None,
  'data_alteracao': None}]


def _nome_norm(value: str | None) -> str:
    return str(value or "").strip().lower()


def _contar_procedimentos_tabela(db: Session, clinica_id: int, tabela_id: int) -> int:
    return int(
        db.query(Procedimento.id)
        .filter(
            Procedimento.clinica_id == int(clinica_id),
            Procedimento.tabela_id == int(tabela_id),
        )
        .count()
    )


def _garantir_tabela_por_nome_ou_codigo(
    db: Session,
    clinica_id: int,
    codigo: int,
    nome: str,
) -> int:
    tabelas = (
        db.query(ProcedimentoTabela)
        .filter(ProcedimentoTabela.clinica_id == int(clinica_id))
        .order_by(ProcedimentoTabela.id.asc())
        .all()
    )
    nome_target = _nome_norm(nome)
    por_nome = [t for t in tabelas if _nome_norm(t.nome) == nome_target]
    por_codigo = [t for t in tabelas if int(t.codigo or 0) == int(codigo)]
    candidatos = por_nome if por_nome else por_codigo

    if candidatos:
        # Se houver duplicidade historica, prioriza a que ja tem procedimentos.
        escolhido = sorted(
            candidatos,
            key=lambda t: (-_contar_procedimentos_tabela(db, clinica_id, int(t.id)), int(t.id)),
        )[0]
        changed = False
        if int(escolhido.codigo or 0) != int(codigo):
            escolhido.codigo = int(codigo)
            changed = True
        if _nome_norm(escolhido.nome) != nome_target:
            escolhido.nome = nome
            changed = True
        if changed:
            db.add(escolhido)
            db.flush()
        print(f"USANDO EXISTENTE {nome} (id={int(escolhido.id)})")
        return int(escolhido.id)

    print(f"CRIANDO TABELA {nome}")
    tabela = ProcedimentoTabela(
        clinica_id=int(clinica_id),
        codigo=int(codigo),
        nome=nome,
        nro_indice=255,
        fonte_pagadora="particular",
        inativo=False,
        tipo_tiss_id=1,
    )
    db.add(tabela)
    db.flush()
    return int(tabela.id)


def seed_procedimentos(db: Session, clinica_id: int) -> int:
    # Protecao contra dupla chamada no mesmo fluxo/transacao.
    guard_key = f"seed_procedimentos_executado_{int(clinica_id)}"
    if bool(db.info.get(guard_key)):
        print(f"USANDO EXISTENTE seed_procedimentos (clinica_id={int(clinica_id)})")
        return 0
    db.info[guard_key] = True

    tabela_id = _garantir_tabela_por_nome_ou_codigo(
        db,
        int(clinica_id),
        codigo=1,
        nome="Tabela Exemplo",
    )
    # Garante tabela PARTICULAR padrao (mesmo vazia).
    _garantir_tabela_por_nome_ou_codigo(
        db,
        int(clinica_id),
        codigo=4,
        nome="PARTICULAR",
    )

    genericos = {
        str(item.codigo or "").strip(): int(item.id)
        for item in db.query(ProcedimentoGenerico)
        .filter(ProcedimentoGenerico.clinica_id == int(clinica_id))
        .all()
        if str(item.codigo or "").strip()
    }
    existentes = {
        int(item.codigo): item
        for item in db.query(Procedimento)
        .filter(
            Procedimento.clinica_id == int(clinica_id),
            Procedimento.tabela_id == int(tabela_id),
        )
        .all()
    }

    total = 0
    for row in PROCEDIMENTOS_PADRAO:
        codigo = int(row.get("codigo") or 0)
        if codigo <= 0:
            continue
        generico_codigo = str(row.get("procedimento_generico_codigo") or "").strip()
        generico_id = genericos.get(generico_codigo) if generico_codigo else None

        item = existentes.get(codigo)
        payload = {
            "nome": row.get("nome") or "",
            "tempo": int(row.get("tempo") or 0),
            "preco": float(row.get("preco") or 0),
            "custo": float(row.get("custo") or 0),
            "custo_lab": float(row.get("custo_lab") or 0),
            "lucro_hora": float(row.get("lucro_hora") or 0),
            "especialidade": row.get("especialidade"),
            "procedimento_generico_id": int(generico_id) if generico_id else None,
            "simbolo_grafico": row.get("simbolo_grafico"),
            "simbolo_grafico_legacy_id": row.get("simbolo_grafico_legacy_id"),
            "mostrar_simbolo": bool(row.get("mostrar_simbolo") or False),
            "garantia_meses": int(row.get("garantia_meses") or 0),
            "forma_cobranca": row.get("forma_cobranca"),
            "valor_repasse": float(row.get("valor_repasse") or 0),
            "preferido": bool(row.get("preferido") or False),
            "inativo": bool(row.get("inativo") or False),
            "observacoes": row.get("observacoes"),
            "data_inclusao": row.get("data_inclusao"),
            "data_alteracao": row.get("data_alteracao"),
        }
        if item is None:
            item = Procedimento(
                clinica_id=int(clinica_id),
                tabela_id=int(tabela_id),
                codigo=int(codigo),
                **payload,
            )
            db.add(item)
        else:
            for key, value in payload.items():
                setattr(item, key, value)
        total += 1

    db.flush()
    return total
